# Generated by Django 2.2 on 2020-07-22 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_address_one', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('facility_address_two', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('facility_city', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('facility_state', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('facility_zip_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('facility_latitude', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('facility_longitude', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('facility_location', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('facility_country_code', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('facility_country', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(null=True)),
                ('description', models.TextField(blank=True, default='', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Description',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.PositiveIntegerField()),
                ('facility_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('facility_phone_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('facility_open', models.DateField(blank=True, null=True)),
                ('facility_fax_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('main_site_facility_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facilities.Address', verbose_name='Address')),
                ('description', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facilities.Description', verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
    ]
